# Generated by Django 2.2.3 on 2019-07-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='seungpang_order',
        ),
    ]
