# Generated by Django 2.2.3 on 2019-07-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190719_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='register_date',
            new_name='register_dttm',
        ),
    ]
