# Generated by Django 2.2.3 on 2019-07-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spuser',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default=1, max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
